### ISSUE TITLE
Come up with a good descriptive project title. Create the landing page and setup the project domain. 

### ISSUE THREAD

**Issue by s-matyukevich** [s-matyukevich/belarus-civil-rights-support#5]
Suggestions for the domain name and project title are welcome. 

I plan to implement a simple landing page using https://www.producthunt.com/ This gives us the opportunity to collect emails of the people who are interested in the project while it is being developed. Also, we'll be able to easily send them marketing emails.

**Comment by s-matyukevich** [comment]
https://civil-rights-fund.org ? Voting here!

**Comment by s-matyukevich** [comment]
This is intended for Russian and Belorussian speaking audience, so sorry for switching languages.

 Я подумываю немного перепрофилировать проект. Для этого есть 2 причины:
1. Люди которые потеряли работу не единственные люди которым сейчас в Беларуси нужна помощь.
1. Судя по анализу разных платежных опций который я делал, самым лучшим вариантом будет полностью децентрализованный вариант: мы просто помогаем людям которые нуждаются в помощи и людям которые могут помочь найти друг друга + помогаем им самостоятельно перводить деньги друг другу 

Исходя из этого я хочу сделать платформу где любой белорус нуждающийся в помощи (финансовой или любой другой) сможет разместить свое видео  а платформа поможет другим людям напрямую перевести ему деньги или просто связаться с ним и помочь любым другим доступным образом. 

Назвать его я подумываю "Дапамажы сябру!" и домен зарегистрировать "https://dapamaji.by" или "https://dapamaji.org" За любые предложения и коментарии буду благодарен.

**Comment by takemyoxygen** [comment]
@s-matyukevich 

Децентрализация - звучит неплохо, но не будет ли проблем у того, кто будет получать платежи (от разных источников)? Я имею в виду декларирование дохода.

Проводить платежи через 1 счет организации (люди переводят деньги на счёт "Дапамажы сябру!", а "Дапамажы сябру!"  переводит нуждающимся в помощи) звучит рискованней (можно повторить судьбу molamola), но, как мне кажется, такое не случится, если у тебя нет родственников-кандидатов в президенты.

Выглядит, что нужна консультация юриста или того, кто уже запускал краудфандинг платформу.

**Comment by s-matyukevich** [comment]
@takemyoxygen 

Я думаю если у платформы будет централизованный рассчетный счет на територии Беларусии возможно 2 варианта:
1. Про нее никто не узнает и она не будет выполнять свою цель.
1. Найдется предлог что бы счет арестовать а компанию закрыть

Касательно налогов получателей, насколько я понимаю есть варианты принимать прямые пожертвования и легально не платить с них налог.

> 3) проиндексированы (увеличены) размеры доходов, освобождаемых от подоходного налога:
> - организаций и индивидуальных предпринимателей, не являющихся местом основной работы, — с 122 руб. до 131 руб., от каждого источника в течение календарного года (п. 23 ст. 208 НК);
> http://www.nalog.gov.by/ru/GL18-PodoxodNalog-s-FL/

но тут да, нужна консультация юриста или того кто уже запускал crouwdfunding platform - я ищу варианты как это сделать

**Comment by LS-eip** [comment]
По поводу доменного имени и идеи проекта в целом, мне кажется, как общая краудфандинговая платформа molamola сейчас имеет бОльше смысла, её знают и уже доверяют, в каком-то виде она продолжает функционировать и ребята при этом ищут способы возобновить платежи через другие банки. Если и пилить сейчас что-то быстрое, то под конкретную цель: помочь тем, кто потерял работу, получил штраф, был выгнан из общаги, лишился премии в результате выражения своей позиции. Чтобы люди увидели поддержку и, может быть,склонились в сторону правды. И название я бы предложила соответствующее. Что-нибудь вроде honestpeople-help (тут отсылка к Честным людям и,в принципе, возможно, действительно есть смысл предложить им сотрудничество). Ещё из вариантов yasnarodom, pomojempravde. Можно ещё подумать,если идея откликается.

**Comment by s-matyukevich** [comment]
@LS-eip спасибо за коментарий!
Я связался с сапортом molamola и спросил их по поводу их планов на дальнейшее развитие - пока жду ответа. Если выясниться что мы делаем одно и то же я с удовольствием присоединюсь к ним. Насколько я понимаю они планируют полностью оставаться в белоруской юрисдикции и начать работать через другие банки (хотя я могу тут ошибаться) Проблема с этим подходом состоит с том что как только они начнут приносить текущей власти проблемы их найдут как закрыть (причем не будут сильно церемониться с формальным соблюдением законности). Если платформа будет помогать людям потерявшим работу из за своей гражданской позиции то это безусловно проблема для влясти и как только таких проектов на molamola станет много их сразу закроют. Поэтому скорее всего, единственный для них вариант продолжить работу в старом режиме это продемонстрировать что они не представляют угрозы.

Итого основная разница должна быть в позиционировании: мы можем сказать что мы помогаем всем, но основная наша фокус группа это люди пострадавшие от действий белорусских властей. (тут я с Вами на 100% согласен)

Насчет названия нужно будет подумать - мне лично больше импонирует посыл что мы помогаем людям чем посыл о том что мы с кем то боремся

**Comment by mmpbel** [comment]
Думаю иметь несколько вариантов сбора денег это хорошо.
У нас в Канаде пока собирают так:
https://www.gofundme.com/f/support-families-of-detained-activists-in-belarus/donate
Т.е. собираются деньги на физ лицо за границей и потом через частных лиц передаются местным волонтёрам. Всё конечно держится на доверии. Мы делали также для помощи с Ковид.
Моламола почему-то отказывался принимать мою канадскую кредитку.
Ещё в Беларуси есть несколько правозащитных организаций, но я не знаю, занимаются ли они финансовой помощью или только юридической.

**Comment by s-matyukevich** [comment]
@mmpbel - для переводов из за границы я планировал пользоваться сервисами наподобие WesternUnion (то есть я хочу помочь конкретному человеку, я нахожу его через платформу и пишу ему в личку, затем он высылает мне свои паспортные данные (которые не являются супер большим секретом) я делаю перевод а он приходит с паспортом в отделение WesternUnion и забирает деньги)

Тоже так себе вариант, но наверное немного лучше чем передавать наличку через волонтеров.

**Comment by mmpbel** [comment]
При переводе неродственнику из-за границы, как я понимаю, надо уплачивать налог. Можно ли этого избежать?
Я ничего не знаю о законодательстве РБ в вопросах благотворительности. Наример, если я в РБ даю чужому человеку деньги в качестве помощи, должен ли получатель уплатить какие-либо налоги?...
Я оплачивал услуги удалённых репетиторов в РБ переводя им деньги прямо на дебетные карты. Они уже сами платили налоги.

**Comment by s-matyukevich** [comment]
Насчет налогов получателя я сейчас изучаю эту тему.

@mmpbel - каким образом вы переводили деньги напрямую на белорусские дебитные карточки?

**Comment by mmpbel** [comment]
@s-matyukevich
В начале я использовал SKRILL (подробности уже не помню, но вроде получатель имел там счёт с привязанной карточкой).
Потом я, будучи в Минске, сделал себе виртуальную карточку БПС, положил на неё некоторую сумму и тратил её удалённо через телефонный онлайн-банкинг. СМС при этом не шлётся, но я в Минске у родственников оставил СИМку на случай, если для некоторых транзакций будет слаться СМС.  Пополнять этот счёт удалённо мне пока не пришлось, но вроде есть такие возможности (https://paysend.com/).
Вроде есть ещё Visa Direct, но я не пробовал. Знакомые вроде слали в Москву.
Я всё время пытался минимизировать комиссию банка :)

**Comment by s-matyukevich** [comment]
Done
